name: Create Google Services JSON File
  env:
    GOOGLE_SERVICES_JSON: ${{ secrets.GCLOUD_CREDENTIALS_BASE64 }}
  run: echo $GCLOUD_CREDENTIALS_BASE64 | base64 -di > ./<folder>/google-credentials.json
